# Generated by Django 4.0.3 on 2022-04-05 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('desk', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='media/', verbose_name='Главное изображение')),
                ('image_slug', models.ImageField(upload_to='media/', verbose_name='Большое Изображение')),
            ],
        ),
    ]
