# Generated by Django 4.0.3 on 2022-04-06 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelBackForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_text_5', models.CharField(max_length=300, verbose_name='Имя клиента')),
                ('form_text_18', models.CharField(max_length=300, verbose_name='Почта клиента')),
                ('form_text_6', models.CharField(max_length=300, verbose_name='Телефон клиента')),
                ('form_text_7', models.TextField(verbose_name='Сообщение от клиента')),
            ],
            options={
                'verbose_name': 'Форму обратной связи',
                'verbose_name_plural': 'Форма обратной связи',
            },
        ),
        migrations.AlterModelOptions(
            name='work',
            options={'verbose_name': 'Наши работы', 'verbose_name_plural': 'Наши работы'},
        ),
    ]
